apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: portfolio-tracker-tls
  namespace: portfolio-tracker
spec:
  secretName: portfolio-tracker-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - portfolio.adamchilders.com
