apiVersion: v1
kind: Namespace
metadata:
  name: portfolio-tracker
  labels:
    name: portfolio-tracker
    app: portfolio-tracker
    environment: production
---
# Optional: Resource quota for the namespace
apiVersion: v1
kind: ResourceQuota
metadata:
  name: portfolio-tracker-quota
  namespace: portfolio-tracker
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 2Gi
    limits.cpu: "2"
    limits.memory: 4Gi
    persistentvolumeclaims: "5"
    pods: "10"
    services: "5"
    secrets: "10"
    configmaps: "10"
---
# Optional: Network policy for security
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: portfolio-tracker-network-policy
  namespace: portfolio-tracker
spec:
  podSelector:
    matchLabels:
      app: portfolio-tracker
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow traffic from within the same namespace
  - from:
    - namespaceSelector:
        matchLabels:
          name: portfolio-tracker
    - podSelector:
        matchLabels:
          app: portfolio-tracker
  # Allow traffic from RKE2 ingress controllers in kube-system namespace
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
  # Allow traffic from any kube-system namespace (alternative selector)
  - from:
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          app.kubernetes.io/name: rke2-ingress-nginx
  # Allow traffic from RKE2 ingress nginx pods
  - from:
    - namespaceSelector: {}
      podSelector:
        matchExpressions:
        - key: app.kubernetes.io/name
          operator: In
          values: ["rke2-ingress-nginx", "ingress-nginx"]
  egress:
  - {} # Allow all egress traffic (for database, redis, external APIs)
