apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: portfolio-tracker-selfsigned
  namespace: portfolio-tracker
spec:
  secretName: portfolio-tracker-tls
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  dnsNames:
  - portfolio.adamchilders.com
  - localhost
